### ISSUE TITLE
[BUG] - New builds created using jupyterlab-conda-store

### ISSUE THREAD

**Issue by iameskild** [conda-incubator/jupyterlab-conda-store#25]
### Describe the bug

I updated my build three times on jupyterlab-conda-store and now I see them as three distinct kernels when I try to select a notebook kernel

<img width="557" alt="Screenshot 2023-09-28 at 15 05 09" src="https://github.com/conda-incubator/jupyterlab-conda-store/assets/42120229/6020c5d4-070b-4dbd-947d-39e88baf080f">

### Expected behavior

Only the "Active" environment should appear as a kernel option.

### How to Reproduce the problem?

Create an env and then in juptyerlab-conda-store, update the build a few times.

### Versions and dependencies used.

conda-store - `2023.9.2`
jupyterlab-conda-store - `2023.9.1`

**Comment by trallard** [comment]
@kcpevey could you help identify if this still an issue (as soon as we can access a deployed JLab-conda-store)
