### ISSUE TITLE
Support for JupyterLab 4

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/jupyterlab-conda-store#29]
### Context

Nebari (a major user of conda-store) will soon move to JupyterLab 4. It'll be nice to start testing if this extension works with JLab 4, and scope any incompatibilities.

### Value and/or benefit

Upgrade to latest tools

### Anything else?

This was discussed in the Nebari meeting today

**Comment by nkaretnikov** [comment]
Status update: not actively working on this because I was asked to focus on other things for now.

**Comment by isumitjha** [comment]
I have created a PR for this and #33 here: #34
