### ISSUE TITLE
[BUG] - Error 404 when running the extension locally with conda-store running in Docker

### ISSUE THREAD

**Issue by sergeygurvich** [conda-incubator/jupyterlab-conda-store#58]
### Describe the bug

The extension is activated, but I can't make it work. I get error 404 in the extension tab window. I verified that the server API and/or UI are running in the Docker container, but it seems that the error is coming independently from the server. 

### Expected behavior

Conda Store UI should load in the extension tab

### How to Reproduce the problem?

1. Clone and start conda-store (or conda-store-ui) using docker compose, like it is described in README
2. Test that conda-store is up (http://0.0.0.0:8080/conda-store/docs)
3. Install JupyterLab (I tried versions 4.0.0 and 4.2.3)
4. Install jupyterlab-conda-store extension. I tried both via `pip install` and via dev version according to README
5. Run JupyterLab
6. Go to Conda Store > Conda Store Package Manager in JupyterLab

### Output

I see the following output in the tab:

Unexpected Application Error!
404 Not Found

### Versions and dependencies used.

JupyterHub 4.0.0 (via pip install) and 4.2.3 (via dev route)
Macox Sonoma 14.1
Node.js v20.9.0
npm@10.1.0 

### Anything else?

<img width="1720" alt="image" src="https://github.com/user-attachments/assets/0422ffa4-7e45-42ee-9a6c-07d94ab5753b">

<img width="1713" alt="image" src="https://github.com/user-attachments/assets/8c8e0f4c-0b07-40f6-8dc4-95f5faf66d59">

**Comment by trallard** [comment]
I am sorry we missed this issue @sergeygurvich  - this should be fixed in the upcoming release of the extension.

**Comment by trallard** [comment]
Closing as we have a release scheduled this week that fixes this issue.
