### ISSUE TITLE
conda-store-ui breaks Jupyter extension (release and update needed)

### ISSUE THREAD

**Issue by gabalafou** [conda-incubator/jupyterlab-conda-store#64]
I'm creating this issue for visibility.

The Conda Store JupyterLab extension depends on Conda Store UI. Currently, the [conda-store-ui version is set to 2024.6.1](https://github.com/conda-incubator/jupyterlab-conda-store/blob/3959df8c82fb363db07f114baa4e53ceb72aa065/package.json#L64), but that version **breaks the JupyterLab extension.** For explanation, refer to:

- https://github.com/conda-incubator/conda-store-ui/pull/429

This conda-store-ui PR will fix conda-store-ui so that it works with this extension. But four things need to happen:

- [x] Merge PR 429 into conda-store-ui
- [x] Cut and publish new release of conda-store-ui 
- [x] Bump conda-store-ui version in this repo's package.json. (Do this in https://github.com/conda-incubator/jupyterlab-conda-store/pull/63.)
- [ ] Cut and publish new release of this extension

This issue can be closed once all four steps above are completed and somebody verifies that they can install and use the new version of this extension in JupyterLab.

**Comment by trallard** [comment]
Will close this issue since release should be handled separately
